# Generated by Django 4.2.13 on 2024-07-06 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('type_of_service', models.CharField(choices=[('PD', 'Pick and Drop'), ('VR', 'Vehicle Rental')], max_length=2)),
                ('contact_info', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('vehicle_type', models.CharField(blank=True, max_length=255, null=True)),
                ('price_per_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cars', models.BooleanField(default=False)),
                ('bikes', models.BooleanField(default=False)),
                ('scooty', models.BooleanField(default=False)),
                ('suvs', models.BooleanField(default=False)),
                ('avg_price_range_per_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
