# Generated by Django 4.2.13 on 2024-07-07 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('provideraccounts', '0002_remove_transportservice_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('school', 'School'), ('tutor', 'Tutor'), ('educational_aid', 'Educational Aid')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('contact_info', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('speciality', models.CharField(blank=True, max_length=100, null=True)),
                ('grade_upto', models.CharField(blank=True, choices=[('pre_school', 'Pre School'), ('nursery', 'Nursery'), ('grade_1', 'Grade 1'), ('grade_2', 'Grade 2'), ('grade_3', 'Grade 3'), ('grade_4', 'Grade 4'), ('grade_5', 'Grade 5'), ('grade_6', 'Grade 6'), ('grade_7', 'Grade 7'), ('grade_8', 'Grade 8'), ('grade_9', 'Grade 9'), ('grade_10', 'Grade 10'), ('grade_11', 'Grade 11'), ('grade_12', 'Grade 12')], max_length=50, null=True)),
                ('streams_offered', models.CharField(blank=True, choices=[('pcm', 'PCM'), ('pcmb', 'PCMB'), ('commerce', 'Commerce'), ('humanities', 'Humanities')], max_length=50, null=True)),
                ('board', models.CharField(blank=True, choices=[('cbse', 'CBSE'), ('icse', 'ICSE'), ('state', 'State Board')], max_length=50, null=True)),
                ('sports_facility', models.BooleanField(default=False)),
                ('computer_lab', models.BooleanField(default=False)),
                ('library', models.BooleanField(default=False)),
                ('subjects_taught', models.CharField(blank=True, max_length=255, null=True)),
                ('avg_pricing', models.CharField(blank=True, max_length=50, null=True)),
                ('hours_per_week', models.IntegerField(blank=True, null=True)),
                ('aid_type', models.CharField(blank=True, choices=[('study_material', 'Provide Study Material'), ('tech_facilities', 'Provide Tech Facilities')], max_length=50, null=True)),
                ('sell_or_donate', models.CharField(blank=True, choices=[('sell', 'Sell'), ('donate', 'Donate')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HealthcareService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('service_type', models.CharField(choices=[('hospital', 'Hospital'), ('clinic', 'Clinic'), ('physiotherapist', 'Physiotherapist'), ('lab', 'Lab'), ('pharmacy', 'Pharmacy')], max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('contact_info', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('speciality', models.CharField(max_length=255)),
                ('emergency_services', models.BooleanField(blank=True, null=True)),
                ('provide_home_service', models.BooleanField(blank=True, null=True)),
                ('provide_all_basic_tests', models.BooleanField(blank=True, null=True)),
                ('specific_tests', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='transportservice',
            constraint=models.UniqueConstraint(fields=('user', 'name', 'type_of_service', 'address', 'latitude', 'longitude'), name='unique_transport_service'),
        ),
        migrations.AddConstraint(
            model_name='transportservice',
            constraint=models.UniqueConstraint(condition=models.Q(('type_of_service', 'PD')), fields=('user', 'name', 'type_of_service', 'vehicle_type', 'price_per_km', 'address', 'contact_info', 'latitude', 'longitude'), name='unique_pick_and_drop_service'),
        ),
        migrations.AddConstraint(
            model_name='transportservice',
            constraint=models.UniqueConstraint(condition=models.Q(('type_of_service', 'VR')), fields=('user', 'name', 'type_of_service', 'address', 'contact_info', 'latitude', 'longitude', 'cars', 'bikes', 'scooty', 'suvs', 'avg_price_range_per_hour'), name='unique_vehicle_rental_service'),
        ),
        migrations.AddField(
            model_name='healthcareservice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='educationalservice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
