# Generated by Django 4.2.13 on 2024-07-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provideraccounts', '0003_educationalservice_healthcareservice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalservice',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='educationalservice',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthcareservice',
            name='emergency_services',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='healthcareservice',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthcareservice',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthcareservice',
            name='provide_all_basic_tests',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='healthcareservice',
            name='provide_home_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='healthcareservice',
            name='service_type',
            field=models.CharField(choices=[('Hospital', 'Hospital'), ('Clinic', 'Clinic'), ('Physiotherapist', 'Physiotherapist'), ('Lab', 'Lab'), ('Pharmacy', 'Pharmacy')], max_length=20),
        ),
        migrations.AlterField(
            model_name='healthcareservice',
            name='speciality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
