# Generated by Django 4.2.13 on 2024-07-07 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provideraccounts', '0004_alter_educationalservice_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationalservice',
            name='grade_upto',
        ),
        migrations.RemoveField(
            model_name='educationalservice',
            name='hours_per_week',
        ),
        migrations.RemoveField(
            model_name='educationalservice',
            name='speciality',
        ),
        migrations.RemoveField(
            model_name='educationalservice',
            name='streams_offered',
        ),
        migrations.AddField(
            model_name='educationalservice',
            name='grade_range',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='educationalservice',
            name='hours_per_day',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='educationalservice',
            name='streams',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='educationalservice',
            name='aid_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='educationalservice',
            name='avg_pricing',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='educationalservice',
            name='board',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='educationalservice',
            name='contact_info',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='educationalservice',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='educationalservice',
            name='sell_or_donate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='educationalservice',
            name='service_type',
            field=models.CharField(choices=[('school', 'School'), ('tutor', 'Tutor'), ('educational_aid', 'Educational Aid')], max_length=20),
        ),
    ]
